# Generated by Django 4.0.3 on 2026-08-20 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, unique=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('rubro', models.CharField(default='Servicios de limpieza', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_negocios', models.CharField(blank=True, max_length=200, null=True)),
                ('segmento', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_proceso', models.CharField(blank=True, max_length=100, null=True)),
                ('portal_compra', models.CharField(blank=True, max_length=100, null=True)),
                ('comprador', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_renglon', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_renglon', models.TextField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('oferente', models.CharField(blank=True, max_length=300, null=True)),
                ('cuit_oferente', models.CharField(blank=True, max_length=20, null=True)),
                ('alternativa', models.CharField(blank=True, max_length=100, null=True)),
                ('especificacion_tecnica', models.TextField(blank=True, null=True)),
                ('cantidad_ofertada', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('precio_unitario_oferta', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('precio_total_oferta', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('moneda_oferta', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_oc', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio_contrato', models.DateField(blank=True, null=True)),
                ('fecha_fin_contrato', models.DateField(blank=True, null=True)),
                ('duracion_contrato', models.IntegerField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=300, null=True)),
                ('cuit_proveedor', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion_contrato', models.TextField(blank=True, null=True)),
                ('cantidad_comprada', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('precio_unitario_compra', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('precio_total_compra', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('moneda_compra', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='InfEje.lote')),
            ],
        ),
    ]
