# Generated by Django 5.2.17 on 2026-08-21 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrolicitacion',
            name='empresa_oferente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_como_oferente', to='InfEje.empresa'),
        ),
        migrations.AddField(
            model_name='registrolicitacion',
            name='empresa_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_como_proveedor', to='InfEje.empresa'),
        ),
    ]
