# Generated by Django 4.0.3 on 2026-08-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0002_registrolicitacion_empresa_oferente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email_3',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
