# Generated by Django 4.0.3 on 2026-08-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0003_empresa_email_2_empresa_email_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
