# Generated by Django 4.0.3 on 2026-08-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0004_empresa_comentarios_empresa_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
