# Generated by Django 4.0.3 on 2026-08-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0005_empresa_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='novedades',
            field=models.TextField(blank=True, null=True),
        ),
    ]
