# Generated by Django 4.0.3 on 2026-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0006_empresa_novedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='archivo_inicial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
