# Generated by Django 4.0.3 on 2026-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0007_empresa_archivo_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_destinatario',
            field=models.CharField(choices=[('persona', 'Persona'), ('empresa', 'Empresa')], default='empresa', max_length=20),
        ),
    ]
