# Generated by Django 4.0.3 on 2026-09-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0008_empresa_tipo_destinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre_pila',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
