# Generated by Django 4.0.3 on 2026-09-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0009_empresa_nombre_pila'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoCarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta', models.CharField(choices=[('1', 'Carta 1'), ('2', 'Carta 2'), ('3', 'Carta 3')], max_length=1)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada')], default='borrador', max_length=20)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('recibio', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=2, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('acciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_cartas', to='InfEje.empresa')),
            ],
        ),
    ]
