# Generated by Django 4.0.3 on 2026-09-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0010_seguimientocarta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carta', models.CharField(choices=[('1', 'Carta 1'), ('2', 'Carta 2'), ('3', 'Carta 3')], max_length=1, unique=True)),
                ('asunto', models.CharField(blank=True, max_length=500, null=True)),
                ('contenido_html', models.TextField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
