# Generated by Django 4.0.3 on 2026-09-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0011_cartaplantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaplantilla',
            name='tipo_destinatario',
            field=models.CharField(choices=[('persona', 'Persona'), ('empresa', 'Empresa')], default='persona', max_length=20),
        ),
        migrations.AlterField(
            model_name='cartaplantilla',
            name='carta',
            field=models.CharField(choices=[('1', 'Carta 1'), ('2', 'Carta 2'), ('3', 'Carta 3')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='cartaplantilla',
            constraint=models.UniqueConstraint(fields=('carta', 'tipo_destinatario'), name='unique_carta_tipo_destinatario'),
        ),
    ]
