# Generated by Django 4.0.3 on 2026-09-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0012_cartaplantilla_tipo_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='genero',
            field=models.CharField(blank=True, choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], max_length=10, null=True),
        ),
    ]
