# Generated by Django 4.0.3 on 2026-09-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0013_empresa_genero'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartaplantilla',
            name='unique_carta_tipo_destinatario',
        ),
        migrations.AddField(
            model_name='cartaplantilla',
            name='genero',
            field=models.CharField(blank=True, choices=[('mujer', 'Mujer'), ('hombre', 'Hombre')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='cartaplantilla',
            constraint=models.UniqueConstraint(fields=('carta', 'tipo_destinatario', 'genero'), name='unique_carta_tipo_genero'),
        ),
    ]
