# Generated by Django 4.0.3 on 2026-09-28 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfEje', '0014_remove_cartaplantilla_unique_carta_tipo_destinatario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoCartasFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('carta1', 'Carta 1'), ('leyo_carta1', 'Leyó Carta 1'), ('respuesta1_fin', 'Respondió Carta 1 - Fin'), ('respuesta1_click', 'Respondió Carta 1 - Click'), ('carta2', 'Carta 2'), ('leyo_carta2', 'Leyó Carta 2'), ('respuesta2_fin', 'Respondió Carta 2 - Fin'), ('respuesta2_click', 'Respondió Carta 2 - Click')], max_length=30)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateField(blank=True, null=True)),
                ('acciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_cartas', to='InfEje.empresa')),
            ],
        ),
        migrations.DeleteModel(
            name='seguimientocarta',
        ),
    ]
